name = "emailapi"
main = "src/index.js"
compatibility_date = "2025-10-31"

[triggers]
email = ["*@uscn.baby"]     # 你的接收域名

[[d1_databases]]
binding = "EmailSql"        # 代码里使用 env.EmailSql
database_name = "email"
database_id = "48aa8997-5322-4777-a77d-6f99cd652d4a"
